# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_nhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 291, 141))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 160, 301, 61))
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 250, 301, 61))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 801, 991))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/123.jpg"))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 440, 131, 41))
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 530, 151, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 340, 161, 31))
        self.label_4.setObjectName("label_4")
        self.nut_2 = QtWidgets.QPushButton(self.centralwidget)
        self.nut_2.setGeometry(QtCore.QRect(380, 340, 111, 31))
        self.nut_2.setStyleSheet("background: rgba(0,0,0,0)")
        self.nut_2.setObjectName("nut_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, -30, 801, 991))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-10, -30, 801, 991))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.nut_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#55007f;\">ĐĂNG NHẬP</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter user name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.pushButton.setText(_translate("MainWindow", "login"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#440066;\">by tiến khoong</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#b90000;\">haven\'t an account?</span></p></body></html>"))
        self.nut_2.setText(_translate("MainWindow", "Register"))
import my_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
