# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'khungthan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_khungchung(object):
    def setupUi(self, khungchung):
        khungchung.setObjectName("khungchung")
        khungchung.resize(761, 605)
        self.centralwidget = QtWidgets.QWidget(khungchung)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.bang_cap = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.bang_cap.setContentsMargins(0, 0, 0, 0)
        self.bang_cap.setObjectName("bang_cap")
        self.capa = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capa.setCheckable(True)
        self.capa.setObjectName("capa")
        self.bang_cap.addWidget(self.capa)
        self.capb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capb.setCheckable(True)
        self.capb.setChecked(False)
        self.capb.setAutoRepeat(False)
        self.capb.setObjectName("capb")
        self.bang_cap.addWidget(self.capb)
        self.capc = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capc.setCheckable(True)
        self.capc.setObjectName("capc")
        self.bang_cap.addWidget(self.capc)
        self.nguphap = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nguphap.setObjectName("nguphap")
        self.bang_cap.addWidget(self.nguphap)
        self.canhan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.canhan.setObjectName("canhan")
        self.bang_cap.addWidget(self.canhan)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 60, 120, 531))
        self.widget.setObjectName("widget")
        self.bang_bai = QtWidgets.QScrollArea(self.widget)
        self.bang_bai.setGeometry(QtCore.QRect(0, 0, 120, 511))
        self.bang_bai.setWidgetResizable(True)
        self.bang_bai.setObjectName("bang_bai")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 118, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.bai1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai1.setGeometry(QtCore.QRect(10, 30, 109, 21))
        self.bai1.setObjectName("bai1")
        self.bai2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai2.setGeometry(QtCore.QRect(10, 60, 109, 23))
        self.bai2.setObjectName("bai2")
        self.bai3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai3.setGeometry(QtCore.QRect(10, 90, 109, 23))
        self.bai3.setObjectName("bai3")
        self.bai4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai4.setGeometry(QtCore.QRect(10, 120, 109, 23))
        self.bai4.setObjectName("bai4")
        self.bai5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai5.setGeometry(QtCore.QRect(10, 150, 109, 23))
        self.bai5.setObjectName("bai5")
        self.bai6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai6.setGeometry(QtCore.QRect(10, 180, 109, 23))
        self.bai6.setObjectName("bai6")
        self.bai9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai9.setGeometry(QtCore.QRect(10, 270, 109, 23))
        self.bai9.setObjectName("bai9")
        self.bai10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai10.setGeometry(QtCore.QRect(10, 300, 109, 23))
        self.bai10.setObjectName("bai10")
        self.bai8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai8.setGeometry(QtCore.QRect(10, 240, 111, 23))
        self.bai8.setObjectName("bai8")
        self.bai7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bai7.setGeometry(QtCore.QRect(10, 210, 109, 23))
        self.bai7.setObjectName("bai7")
        self.bang_bai.setWidget(self.scrollAreaWidgetContents)
        self.bang_ngu_phap = QtWidgets.QWidget(self.centralwidget)
        self.bang_ngu_phap.setGeometry(QtCore.QRect(150, 70, 591, 511))
        self.bang_ngu_phap.setObjectName("bang_ngu_phap")
        self.timkiem = QtWidgets.QLineEdit(self.bang_ngu_phap)
        self.timkiem.setGeometry(QtCore.QRect(310, 10, 281, 21))
        self.timkiem.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);")
        self.timkiem.setText("")
        self.timkiem.setObjectName("timkiem")
        self.pushButton_tmkiem = QtWidgets.QPushButton(self.bang_ngu_phap)
        self.pushButton_tmkiem.setGeometry(QtCore.QRect(510, 10, 75, 21))
        self.pushButton_tmkiem.setStyleSheet("border-radius: 10px;\n"
"color: green;\n"
"background: rgba(231, 231, 231, 0.5);")
        self.pushButton_tmkiem.setObjectName("pushButton_tmkiem")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.bang_ngu_phap)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 50, 581, 461))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 579, 459))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents_3)
        self.listView.setStyleSheet("border-radius: 10px;\n"
"\n"
"background: rgba(224, 238, 238, 0.5);")
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.listView_5 = QtWidgets.QListView(self.scrollAreaWidgetContents_3)
        self.listView_5.setStyleSheet("border-radius: 10px;\n"
"\n"
"background: rgba(224, 238, 238, 0.5);")
        self.listView_5.setObjectName("listView_5")
        self.verticalLayout_2.addWidget(self.listView_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.bang_ndkt = QtWidgets.QTabWidget(self.centralwidget)
        self.bang_ndkt.setGeometry(QtCore.QRect(140, 70, 611, 511))
        self.bang_ndkt.setObjectName("bang_ndkt")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.stackednghe = QtWidgets.QStackedWidget(self.tab)
        self.stackednghe.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackednghe.setObjectName("stackednghe")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.text_viet_nghe1 = QtWidgets.QTextEdit(self.page)
        self.text_viet_nghe1.setGeometry(QtCore.QRect(20, 50, 521, 221))
        self.text_viet_nghe1.setMouseTracking(True)
        self.text_viet_nghe1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_viet_nghe1.setObjectName("text_viet_nghe1")
        self.text_en_nghe_1 = QtWidgets.QTextEdit(self.page)
        self.text_en_nghe_1.setGeometry(QtCore.QRect(20, 280, 521, 61))
        self.text_en_nghe_1.setMouseTracking(True)
        self.text_en_nghe_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_nghe_1.setObjectName("text_en_nghe_1")
        self.tl_nghe_1 = QtWidgets.QLineEdit(self.page)
        self.tl_nghe_1.setGeometry(QtCore.QRect(20, 350, 411, 61))
        self.tl_nghe_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_nghe_1.setText("")
        self.tl_nghe_1.setObjectName("tl_nghe_1")
        self.dan_nghe_1 = QtWidgets.QTextEdit(self.page)
        self.dan_nghe_1.setGeometry(QtCore.QRect(60, 420, 491, 41))
        self.dan_nghe_1.setMouseTracking(True)
        self.dan_nghe_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.dan_nghe_1.setObjectName("dan_nghe_1")
        self.pushButton_12 = QtWidgets.QPushButton(self.page)
        self.pushButton_12.setGeometry(QtCore.QRect(450, 350, 81, 61))
        self.pushButton_12.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_12.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/ghiam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.stackednghe.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.text_anh_nghe_2 = QtWidgets.QTextEdit(self.page_2)
        self.text_anh_nghe_2.setGeometry(QtCore.QRect(30, 260, 521, 61))
        self.text_anh_nghe_2.setMouseTracking(True)
        self.text_anh_nghe_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_anh_nghe_2.setObjectName("text_anh_nghe_2")
        self.text_viet_nghe_5 = QtWidgets.QTextEdit(self.page_2)
        self.text_viet_nghe_5.setGeometry(QtCore.QRect(30, 40, 521, 211))
        self.text_viet_nghe_5.setMouseTracking(True)
        self.text_viet_nghe_5.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_viet_nghe_5.setObjectName("text_viet_nghe_5")
        self.tl_nghe_2 = QtWidgets.QLineEdit(self.page_2)
        self.tl_nghe_2.setGeometry(QtCore.QRect(30, 330, 411, 61))
        self.tl_nghe_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_nghe_2.setText("")
        self.tl_nghe_2.setObjectName("tl_nghe_2")
        self.tbao_nghe_2 = QtWidgets.QTextEdit(self.page_2)
        self.tbao_nghe_2.setGeometry(QtCore.QRect(40, 410, 491, 41))
        self.tbao_nghe_2.setMouseTracking(True)
        self.tbao_nghe_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_nghe_2.setObjectName("tbao_nghe_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_11.setGeometry(QtCore.QRect(460, 330, 81, 61))
        self.pushButton_11.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.stackednghe.addWidget(self.page_2)
        self.bang_ndkt.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.stackednoi = QtWidgets.QStackedWidget(self.tab_2)
        self.stackednoi.setGeometry(QtCore.QRect(10, 10, 591, 471))
        self.stackednoi.setObjectName("stackednoi")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.text_vi_noi_2 = QtWidgets.QTextEdit(self.page_4)
        self.text_vi_noi_2.setGeometry(QtCore.QRect(20, 40, 531, 221))
        self.text_vi_noi_2.setMouseTracking(True)
        self.text_vi_noi_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_noi_2.setObjectName("text_vi_noi_2")
        self.tl_noi_2 = QtWidgets.QLineEdit(self.page_4)
        self.tl_noi_2.setGeometry(QtCore.QRect(60, 350, 411, 61))
        self.tl_noi_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_noi_2.setText("")
        self.tl_noi_2.setObjectName("tl_noi_2")
        self.tbao_noi_2 = QtWidgets.QTextEdit(self.page_4)
        self.tbao_noi_2.setGeometry(QtCore.QRect(60, 420, 491, 41))
        self.tbao_noi_2.setMouseTracking(True)
        self.tbao_noi_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_noi_2.setObjectName("tbao_noi_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 280, 81, 61))
        self.pushButton_10.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.stackednoi.addWidget(self.page_4)
        self.bang_ndkt.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.stackeddoc_2 = QtWidgets.QStackedWidget(self.tab_4)
        self.stackeddoc_2.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackeddoc_2.setObjectName("stackeddoc_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.text_en_doc_1 = QtWidgets.QTextEdit(self.page_5)
        self.text_en_doc_1.setGeometry(QtCore.QRect(20, 50, 541, 221))
        self.text_en_doc_1.setMouseTracking(True)
        self.text_en_doc_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_doc_1.setObjectName("text_en_doc_1")
        self.text_vi_doc_1 = QtWidgets.QTextEdit(self.page_5)
        self.text_vi_doc_1.setGeometry(QtCore.QRect(30, 280, 521, 61))
        self.text_vi_doc_1.setMouseTracking(True)
        self.text_vi_doc_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_doc_1.setObjectName("text_vi_doc_1")
        self.tl_doc_1 = QtWidgets.QLineEdit(self.page_5)
        self.tl_doc_1.setGeometry(QtCore.QRect(30, 360, 411, 61))
        self.tl_doc_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_doc_1.setText("")
        self.tl_doc_1.setObjectName("tl_doc_1")
        self.tbao_doc_1 = QtWidgets.QTextEdit(self.page_5)
        self.tbao_doc_1.setGeometry(QtCore.QRect(50, 430, 491, 41))
        self.tbao_doc_1.setMouseTracking(True)
        self.tbao_doc_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_doc_1.setObjectName("tbao_doc_1")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_14.setGeometry(QtCore.QRect(460, 360, 81, 61))
        self.pushButton_14.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackeddoc_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.text_en_doc_2 = QtWidgets.QTextEdit(self.page_6)
        self.text_en_doc_2.setGeometry(QtCore.QRect(30, 270, 531, 71))
        self.text_en_doc_2.setMouseTracking(True)
        self.text_en_doc_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_doc_2.setObjectName("text_en_doc_2")
        self.text_vi_doc_2 = QtWidgets.QTextEdit(self.page_6)
        self.text_vi_doc_2.setGeometry(QtCore.QRect(30, 40, 521, 221))
        self.text_vi_doc_2.setMouseTracking(True)
        self.text_vi_doc_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_doc_2.setObjectName("text_vi_doc_2")
        self.tl_doc_2 = QtWidgets.QLineEdit(self.page_6)
        self.tl_doc_2.setGeometry(QtCore.QRect(20, 350, 411, 61))
        self.tl_doc_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_doc_2.setText("")
        self.tl_doc_2.setObjectName("tl_doc_2")
        self.tbao_doc_2 = QtWidgets.QTextEdit(self.page_6)
        self.tbao_doc_2.setGeometry(QtCore.QRect(40, 420, 491, 41))
        self.tbao_doc_2.setMouseTracking(True)
        self.tbao_doc_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_doc_2.setObjectName("tbao_doc_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_13.setGeometry(QtCore.QRect(460, 350, 81, 61))
        self.pushButton_13.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.stackeddoc_2.addWidget(self.page_6)
        self.bang_ndkt.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.stackedviet_3 = QtWidgets.QStackedWidget(self.tab_5)
        self.stackedviet_3.setGeometry(QtCore.QRect(10, 10, 581, 471))
        self.stackedviet_3.setObjectName("stackedviet_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.text_en_viet_1 = QtWidgets.QTextEdit(self.page_7)
        self.text_en_viet_1.setGeometry(QtCore.QRect(20, 20, 541, 251))
        self.text_en_viet_1.setMouseTracking(True)
        self.text_en_viet_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_viet_1.setObjectName("text_en_viet_1")
        self.text_vi_viet_1 = QtWidgets.QTextEdit(self.page_7)
        self.text_vi_viet_1.setGeometry(QtCore.QRect(40, 280, 521, 61))
        self.text_vi_viet_1.setMouseTracking(True)
        self.text_vi_viet_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_viet_1.setObjectName("text_vi_viet_1")
        self.tl_viet_1 = QtWidgets.QLineEdit(self.page_7)
        self.tl_viet_1.setGeometry(QtCore.QRect(20, 350, 411, 61))
        self.tl_viet_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_viet_1.setText("")
        self.tl_viet_1.setObjectName("tl_viet_1")
        self.tbao_viet_1 = QtWidgets.QTextEdit(self.page_7)
        self.tbao_viet_1.setGeometry(QtCore.QRect(40, 420, 491, 41))
        self.tbao_viet_1.setMouseTracking(True)
        self.tbao_viet_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_viet_1.setObjectName("tbao_viet_1")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_16.setGeometry(QtCore.QRect(450, 350, 81, 61))
        self.pushButton_16.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.stackedviet_3.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.text_en_viet_2 = QtWidgets.QTextEdit(self.page_8)
        self.text_en_viet_2.setGeometry(QtCore.QRect(20, 290, 521, 61))
        self.text_en_viet_2.setMouseTracking(True)
        self.text_en_viet_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_viet_2.setObjectName("text_en_viet_2")
        self.text_vi_viet_2 = QtWidgets.QTextEdit(self.page_8)
        self.text_vi_viet_2.setGeometry(QtCore.QRect(20, 20, 521, 261))
        self.text_vi_viet_2.setMouseTracking(True)
        self.text_vi_viet_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_viet_2.setObjectName("text_vi_viet_2")
        self.tl_viet_2 = QtWidgets.QLineEdit(self.page_8)
        self.tl_viet_2.setGeometry(QtCore.QRect(20, 360, 411, 61))
        self.tl_viet_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_viet_2.setText("")
        self.tl_viet_2.setObjectName("tl_viet_2")
        self.tbao_viet_2 = QtWidgets.QTextEdit(self.page_8)
        self.tbao_viet_2.setGeometry(QtCore.QRect(40, 430, 491, 41))
        self.tbao_viet_2.setMouseTracking(True)
        self.tbao_viet_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_viet_2.setObjectName("tbao_viet_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_15.setGeometry(QtCore.QRect(450, 360, 81, 61))
        self.pushButton_15.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.stackedviet_3.addWidget(self.page_8)
        self.bang_ndkt.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.stackedkt_4 = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedkt_4.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackedkt_4.setObjectName("stackedkt_4")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.stackedkt_5 = QtWidgets.QStackedWidget(self.page_11)
        self.stackedkt_5.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackedkt_5.setObjectName("stackedkt_5")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.text_en_noi_2 = QtWidgets.QTextEdit(self.page_12)
        self.text_en_noi_2.setGeometry(QtCore.QRect(40, 90, 521, 61))
        self.text_en_noi_2.setMouseTracking(True)
        self.text_en_noi_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_noi_2.setObjectName("text_en_noi_2")
        self.text_vi_noi_3 = QtWidgets.QTextEdit(self.page_12)
        self.text_vi_noi_3.setGeometry(QtCore.QRect(40, 180, 521, 61))
        self.text_vi_noi_3.setMouseTracking(True)
        self.text_vi_noi_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_noi_3.setObjectName("text_vi_noi_3")
        self.tl_noi_3 = QtWidgets.QLineEdit(self.page_12)
        self.tl_noi_3.setGeometry(QtCore.QRect(110, 300, 411, 61))
        self.tl_noi_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_noi_3.setText("")
        self.tl_noi_3.setObjectName("tl_noi_3")
        self.label_11 = QtWidgets.QLabel(self.page_12)
        self.label_11.setGeometry(QtCore.QRect(30, 300, 61, 71))
        self.label_11.setObjectName("label_11")
        self.tbao_noi_3 = QtWidgets.QTextEdit(self.page_12)
        self.tbao_noi_3.setGeometry(QtCore.QRect(60, 410, 491, 41))
        self.tbao_noi_3.setMouseTracking(True)
        self.tbao_noi_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_noi_3.setObjectName("tbao_noi_3")
        self.stackedkt_5.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.text_vi_kt_3 = QtWidgets.QTextEdit(self.page_13)
        self.text_vi_kt_3.setGeometry(QtCore.QRect(40, 70, 521, 61))
        self.text_vi_kt_3.setMouseTracking(True)
        self.text_vi_kt_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_3.setObjectName("text_vi_kt_3")
        self.tl_kt_3 = QtWidgets.QLineEdit(self.page_13)
        self.tl_kt_3.setGeometry(QtCore.QRect(90, 280, 411, 61))
        self.tl_kt_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_3.setText("")
        self.tl_kt_3.setObjectName("tl_kt_3")
        self.tbao_kt_3 = QtWidgets.QTextEdit(self.page_13)
        self.tbao_kt_3.setGeometry(QtCore.QRect(70, 390, 491, 41))
        self.tbao_kt_3.setMouseTracking(True)
        self.tbao_kt_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_3.setObjectName("tbao_kt_3")
        self.label_12 = QtWidgets.QLabel(self.page_13)
        self.label_12.setGeometry(QtCore.QRect(10, 400, 51, 20))
        self.label_12.setObjectName("label_12")
        self.ghi_amkt = QtWidgets.QPushButton(self.page_13)
        self.ghi_amkt.setGeometry(QtCore.QRect(230, 170, 81, 61))
        self.ghi_amkt.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.ghi_amkt.setText("")
        self.ghi_amkt.setIcon(icon)
        self.ghi_amkt.setIconSize(QtCore.QSize(50, 50))
        self.ghi_amkt.setObjectName("ghi_amkt")
        self.stackedkt_5.addWidget(self.page_13)
        self.stackedkt_4.addWidget(self.page_11)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedkt_6 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedkt_6.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackedkt_6.setObjectName("stackedkt_6")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.stackednoi_7 = QtWidgets.QStackedWidget(self.page_14)
        self.stackednoi_7.setGeometry(QtCore.QRect(0, 0, 601, 471))
        self.stackednoi_7.setObjectName("stackednoi_7")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.text_en_noi_3 = QtWidgets.QTextEdit(self.page_15)
        self.text_en_noi_3.setGeometry(QtCore.QRect(40, 90, 521, 61))
        self.text_en_noi_3.setMouseTracking(True)
        self.text_en_noi_3.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_noi_3.setObjectName("text_en_noi_3")
        self.text_vi_noi_4 = QtWidgets.QTextEdit(self.page_15)
        self.text_vi_noi_4.setGeometry(QtCore.QRect(40, 180, 521, 61))
        self.text_vi_noi_4.setMouseTracking(True)
        self.text_vi_noi_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_noi_4.setObjectName("text_vi_noi_4")
        self.tl_noi_4 = QtWidgets.QLineEdit(self.page_15)
        self.tl_noi_4.setGeometry(QtCore.QRect(110, 300, 411, 61))
        self.tl_noi_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_noi_4.setText("")
        self.tl_noi_4.setObjectName("tl_noi_4")
        self.label_13 = QtWidgets.QLabel(self.page_15)
        self.label_13.setGeometry(QtCore.QRect(30, 300, 61, 71))
        self.label_13.setObjectName("label_13")
        self.tbao_noi_4 = QtWidgets.QTextEdit(self.page_15)
        self.tbao_noi_4.setGeometry(QtCore.QRect(60, 410, 491, 41))
        self.tbao_noi_4.setMouseTracking(True)
        self.tbao_noi_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_noi_4.setObjectName("tbao_noi_4")
        self.stackednoi_7.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.text_vi_kt_4 = QtWidgets.QTextEdit(self.page_16)
        self.text_vi_kt_4.setGeometry(QtCore.QRect(40, 70, 521, 61))
        self.text_vi_kt_4.setMouseTracking(True)
        self.text_vi_kt_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_4.setObjectName("text_vi_kt_4")
        self.tl_kt_4 = QtWidgets.QLineEdit(self.page_16)
        self.tl_kt_4.setGeometry(QtCore.QRect(90, 280, 411, 61))
        self.tl_kt_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_4.setText("")
        self.tl_kt_4.setObjectName("tl_kt_4")
        self.tbao_kt_4 = QtWidgets.QTextEdit(self.page_16)
        self.tbao_kt_4.setGeometry(QtCore.QRect(70, 390, 491, 41))
        self.tbao_kt_4.setMouseTracking(True)
        self.tbao_kt_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_4.setObjectName("tbao_kt_4")
        self.label_14 = QtWidgets.QLabel(self.page_16)
        self.label_14.setGeometry(QtCore.QRect(10, 400, 51, 20))
        self.label_14.setObjectName("label_14")
        self.ghi_am_2 = QtWidgets.QPushButton(self.page_16)
        self.ghi_am_2.setGeometry(QtCore.QRect(230, 170, 81, 61))
        self.ghi_am_2.setStyleSheet("\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.ghi_am_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ghiam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ghi_am_2.setIcon(icon1)
        self.ghi_am_2.setIconSize(QtCore.QSize(50, 50))
        self.ghi_am_2.setObjectName("ghi_am_2")
        self.stackednoi_7.addWidget(self.page_16)
        self.stackedkt_6.addWidget(self.page_14)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.stackedkt_6.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.text_en_kt_5 = QtWidgets.QTextEdit(self.page_18)
        self.text_en_kt_5.setGeometry(QtCore.QRect(40, 90, 521, 61))
        self.text_en_kt_5.setMouseTracking(True)
        self.text_en_kt_5.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_kt_5.setObjectName("text_en_kt_5")
        self.text_vi_kt_5 = QtWidgets.QTextEdit(self.page_18)
        self.text_vi_kt_5.setGeometry(QtCore.QRect(40, 180, 521, 61))
        self.text_vi_kt_5.setMouseTracking(True)
        self.text_vi_kt_5.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_5.setObjectName("text_vi_kt_5")
        self.tl_kt_5 = QtWidgets.QLineEdit(self.page_18)
        self.tl_kt_5.setGeometry(QtCore.QRect(110, 300, 411, 61))
        self.tl_kt_5.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_5.setText("")
        self.tl_kt_5.setObjectName("tl_kt_5")
        self.label_15 = QtWidgets.QLabel(self.page_18)
        self.label_15.setGeometry(QtCore.QRect(30, 300, 61, 71))
        self.label_15.setObjectName("label_15")
        self.tbao_kt_5 = QtWidgets.QTextEdit(self.page_18)
        self.tbao_kt_5.setGeometry(QtCore.QRect(60, 410, 491, 41))
        self.tbao_kt_5.setMouseTracking(True)
        self.tbao_kt_5.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_5.setObjectName("tbao_kt_5")
        self.stackedkt_6.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.text_en_kt_4 = QtWidgets.QTextEdit(self.page_19)
        self.text_en_kt_4.setGeometry(QtCore.QRect(40, 50, 521, 61))
        self.text_en_kt_4.setMouseTracking(True)
        self.text_en_kt_4.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_kt_4.setObjectName("text_en_kt_4")
        self.text_vi_kt_6 = QtWidgets.QTextEdit(self.page_19)
        self.text_vi_kt_6.setGeometry(QtCore.QRect(40, 140, 521, 61))
        self.text_vi_kt_6.setMouseTracking(True)
        self.text_vi_kt_6.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_6.setObjectName("text_vi_kt_6")
        self.tl_kt_6 = QtWidgets.QLineEdit(self.page_19)
        self.tl_kt_6.setGeometry(QtCore.QRect(90, 270, 411, 61))
        self.tl_kt_6.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_6.setText("")
        self.tl_kt_6.setObjectName("tl_kt_6")
        self.tbao_kt_6 = QtWidgets.QTextEdit(self.page_19)
        self.tbao_kt_6.setGeometry(QtCore.QRect(80, 410, 491, 41))
        self.tbao_kt_6.setMouseTracking(True)
        self.tbao_kt_6.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_6.setObjectName("tbao_kt_6")
        self.label_16 = QtWidgets.QLabel(self.page_19)
        self.label_16.setGeometry(QtCore.QRect(10, 410, 51, 20))
        self.label_16.setObjectName("label_16")
        self.stackedkt_6.addWidget(self.page_19)
        self.stackedkt_4.addWidget(self.page_3)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.text_en_kt_1 = QtWidgets.QTextEdit(self.page_9)
        self.text_en_kt_1.setGeometry(QtCore.QRect(40, 90, 521, 61))
        self.text_en_kt_1.setMouseTracking(True)
        self.text_en_kt_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_kt_1.setObjectName("text_en_kt_1")
        self.text_vi_kt_1 = QtWidgets.QTextEdit(self.page_9)
        self.text_vi_kt_1.setGeometry(QtCore.QRect(40, 180, 521, 61))
        self.text_vi_kt_1.setMouseTracking(True)
        self.text_vi_kt_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_1.setObjectName("text_vi_kt_1")
        self.tl_kt_1 = QtWidgets.QLineEdit(self.page_9)
        self.tl_kt_1.setGeometry(QtCore.QRect(110, 300, 411, 61))
        self.tl_kt_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_1.setText("")
        self.tl_kt_1.setObjectName("tl_kt_1")
        self.label_9 = QtWidgets.QLabel(self.page_9)
        self.label_9.setGeometry(QtCore.QRect(30, 300, 61, 71))
        self.label_9.setObjectName("label_9")
        self.tbao_kt_1 = QtWidgets.QTextEdit(self.page_9)
        self.tbao_kt_1.setGeometry(QtCore.QRect(60, 410, 491, 41))
        self.tbao_kt_1.setMouseTracking(True)
        self.tbao_kt_1.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_1.setObjectName("tbao_kt_1")
        self.stackedkt_4.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.text_en_kt_2 = QtWidgets.QTextEdit(self.page_10)
        self.text_en_kt_2.setGeometry(QtCore.QRect(40, 50, 521, 61))
        self.text_en_kt_2.setMouseTracking(True)
        self.text_en_kt_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_en_kt_2.setObjectName("text_en_kt_2")
        self.text_vi_kt_2 = QtWidgets.QTextEdit(self.page_10)
        self.text_vi_kt_2.setGeometry(QtCore.QRect(40, 140, 521, 61))
        self.text_vi_kt_2.setMouseTracking(True)
        self.text_vi_kt_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.text_vi_kt_2.setObjectName("text_vi_kt_2")
        self.tl_kt_2 = QtWidgets.QLineEdit(self.page_10)
        self.tl_kt_2.setGeometry(QtCore.QRect(90, 270, 411, 61))
        self.tl_kt_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 212, 231, 0.5);\n"
"")
        self.tl_kt_2.setText("")
        self.tl_kt_2.setObjectName("tl_kt_2")
        self.tbao_kt_2 = QtWidgets.QTextEdit(self.page_10)
        self.tbao_kt_2.setGeometry(QtCore.QRect(80, 410, 491, 41))
        self.tbao_kt_2.setMouseTracking(True)
        self.tbao_kt_2.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background: rgba(231, 231, 231, 0.5);\n"
"")
        self.tbao_kt_2.setObjectName("tbao_kt_2")
        self.label_10 = QtWidgets.QLabel(self.page_10)
        self.label_10.setGeometry(QtCore.QRect(10, 410, 51, 20))
        self.label_10.setObjectName("label_10")
        self.stackedkt_4.addWidget(self.page_10)
        self.bang_ndkt.addTab(self.tab_3, "")
        khungchung.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(khungchung)
        self.statusbar.setObjectName("statusbar")
        khungchung.setStatusBar(self.statusbar)

        self.retranslateUi(khungchung)
        self.bang_ndkt.setCurrentIndex(1)
        self.stackednghe.setCurrentIndex(0)
        self.stackednoi.setCurrentIndex(0)
        self.stackeddoc_2.setCurrentIndex(0)
        self.stackedviet_3.setCurrentIndex(0)
        self.stackedkt_4.setCurrentIndex(0)
        self.stackedkt_5.setCurrentIndex(1)
        self.stackedkt_6.setCurrentIndex(2)
        self.stackednoi_7.setCurrentIndex(1)
        self.capa.clicked['bool'].connect(self.bang_bai.setVisible) # type: ignore
        self.capc.clicked['bool'].connect(self.bang_bai.setVisible) # type: ignore
        self.capa.toggled['bool'].connect(self.bang_bai.setHidden) # type: ignore
        self.capb.toggled['bool'].connect(self.bang_bai.setHidden) # type: ignore
        self.capc.toggled['bool'].connect(self.bang_bai.setHidden) # type: ignore
        self.capc.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.nguphap.clicked['bool'].connect(self.bang_ngu_phap.show) # type: ignore
        self.capb.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.capa.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai1.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai2.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai3.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai4.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai5.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai6.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai9.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.bai10.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.nguphap.clicked['bool'].connect(self.bang_ndkt.hide) # type: ignore
        self.capc.clicked['bool'].connect(self.bang_ndkt.hide) # type: ignore
        self.capb.clicked['bool'].connect(self.bang_ndkt.hide) # type: ignore
        self.capa.clicked['bool'].connect(self.bang_ndkt.hide) # type: ignore
        self.bai1.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai2.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai4.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai3.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai5.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai6.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai9.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai10.clicked['bool'].connect(khungchung.show) # type: ignore
        self.bai7.clicked['bool'].connect(self.bang_ndkt.show) # type: ignore
        self.bai7.clicked['bool'].connect(self.bang_ngu_phap.hide) # type: ignore
        self.capb.clicked['bool'].connect(self.bang_bai.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(khungchung)

    def retranslateUi(self, khungchung):
        _translate = QtCore.QCoreApplication.translate
        khungchung.setWindowTitle(_translate("khungchung", "MainWindow"))
        self.capa.setText(_translate("khungchung", "Cấp A"))
        self.capb.setText(_translate("khungchung", "Cấp B"))
        self.capc.setText(_translate("khungchung", "Cấp C"))
        self.nguphap.setText(_translate("khungchung", "ngữ pháp"))
        self.canhan.setText(_translate("khungchung", "cá nhân"))
        self.bai1.setText(_translate("khungchung", "bài 1"))
        self.bai2.setText(_translate("khungchung", "bài 2"))
        self.bai3.setText(_translate("khungchung", "bài 3"))
        self.bai4.setText(_translate("khungchung", "bài 4"))
        self.bai5.setText(_translate("khungchung", "bài 5"))
        self.bai6.setText(_translate("khungchung", "bài 6"))
        self.bai9.setText(_translate("khungchung", "bài 9"))
        self.bai10.setText(_translate("khungchung", "bài 10"))
        self.bai8.setText(_translate("khungchung", "bài 8"))
        self.bai7.setText(_translate("khungchung", "bài 7"))
        self.pushButton_tmkiem.setText(_translate("khungchung", "TÌM KIẾM"))
        self.text_viet_nghe1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_en_nghe_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_nghe_1.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.dan_nghe_1.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_anh_nghe_2.setPlaceholderText(_translate("khungchung", "câu hỏi trộn"))
        self.text_viet_nghe_5.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_nghe_2.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_nghe_2.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.bang_ndkt.setTabText(self.bang_ndkt.indexOf(self.tab), _translate("khungchung", "nói_part 1"))
        self.text_vi_noi_2.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_noi_2.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_noi_2.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.bang_ndkt.setTabText(self.bang_ndkt.indexOf(self.tab_2), _translate("khungchung", "nói_part 2"))
        self.text_en_doc_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_doc_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_doc_1.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_doc_1.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_en_doc_2.setPlaceholderText(_translate("khungchung", "câu hỏi trộn"))
        self.text_vi_doc_2.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_doc_2.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_doc_2.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.bang_ndkt.setTabText(self.bang_ndkt.indexOf(self.tab_4), _translate("khungchung", "nói_part 3"))
        self.text_en_viet_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_viet_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_viet_1.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_viet_1.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_en_viet_2.setPlaceholderText(_translate("khungchung", "câu hỏi trộn"))
        self.text_vi_viet_2.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_viet_2.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_viet_2.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.bang_ndkt.setTabText(self.bang_ndkt.indexOf(self.tab_5), _translate("khungchung", "nói_part 4"))
        self.text_en_noi_2.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_noi_3.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_noi_3.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.label_11.setText(_translate("khungchung", "Câu trả lời:"))
        self.tbao_noi_3.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_vi_kt_3.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_3.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_kt_3.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.label_12.setText(_translate("khungchung", "thông báo"))
        self.text_en_noi_3.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_noi_4.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_noi_4.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.label_13.setText(_translate("khungchung", "Câu trả lời:"))
        self.tbao_noi_4.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_vi_kt_4.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_4.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_kt_4.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.label_14.setText(_translate("khungchung", "thông báo"))
        self.text_en_kt_5.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_kt_5.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_5.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.label_15.setText(_translate("khungchung", "Câu trả lời:"))
        self.tbao_kt_5.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_en_kt_4.setPlaceholderText(_translate("khungchung", "câu hỏi "))
        self.text_vi_kt_6.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_6.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_kt_6.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.label_16.setText(_translate("khungchung", "thông báo"))
        self.text_en_kt_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng anh"))
        self.text_vi_kt_1.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_1.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.label_9.setText(_translate("khungchung", "Câu trả lời:"))
        self.tbao_kt_1.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.text_en_kt_2.setPlaceholderText(_translate("khungchung", "câu hỏi "))
        self.text_vi_kt_2.setPlaceholderText(_translate("khungchung", "câu hỏi tiếng việt"))
        self.tl_kt_2.setPlaceholderText(_translate("khungchung", "nhập câu trả lời"))
        self.tbao_kt_2.setPlaceholderText(_translate("khungchung", "thông báo đáp án"))
        self.label_10.setText(_translate("khungchung", "thông báo"))
        self.bang_ndkt.setTabText(self.bang_ndkt.indexOf(self.tab_3), _translate("khungchung", "kiểm tra"))
import GHI_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    khungchung = QtWidgets.QMainWindow()
    ui = Ui_khungchung()
    ui.setupUi(khungchung)
    khungchung.show()
    sys.exit(app.exec_())
